services:
  letsencrypt:
    container_name: 'certbot-service'
    image: certbot/certbot
    command:
      - certonly
      - --webroot
      - -w
      - /var/www/acme_challenge
      - -d
      - thiago.solutions
      - -d
      - www.thiago.solutions
      - --text
      - --agree-tos
      - --email
      - thiago_marketingdigital@hotmail.com
      - --rsa-key-size
      - "4096"
      - --verbose
      - --keep-until-expiring
      - --preferred-challenges=http

    volumes:
      - './ssl:/etc/letsencrypt'
      - './ssl/acme_challenge:/var/www/acme_challenge'
    environment:
      - TERM=xterm
