services:
  nginx:
    image: nginx:latest
    container_name: nginx-ssl
    ports:
      - "80:80"   
      - "443:443"   
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/letsencrypt
    depends_on:
      - backend  
    restart: unless-stopped
    networks:
      - backend-net

  backend:
    build: .
    container_name: backend
    expose:
      - "3000"  # Expõe a porta 3000 para a rede interna
    networks:
      - backend-net
    restart: always

networks:
  backend-net:
    driver: bridge
